pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
        - "base=main"
        - "draft=false"
    actions:
      merge:
        method: squash
        commit_message_template: >
          {{ title }} (#{{ number }})

          {{ body }}

          Pull Request: https://github.com/{{ repository-full-name }}/pulls/{{ number }}
