queue_rules:
  - name: dev
    conditions: []

pull_request_rules:
  - name: automerge to dev
    conditions:
      - and:
        - "base=dev"
        - "-draft"
    actions:
      queue:
        name: dev
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}

          Pull Request: https://github.com/{{ repository_full_name }}/pull/{{ number }}
      backport:
        branches:
          - prod
        assignees:
          - "{{ author }}"
