# queue_rules:
#   - name: dev
#     conditions: []
#   - name: prod
#     conditions: []

pull_request_rules:
  - name: convert wip to draft
    conditions:
      - "#check-failure>0"
    actions:
      edit:
        draft: True
  
  - name: request review when status checks pass
    conditions:
      - "#check-failure=0"
    actions:
      edit:
        draft: False

  - name: automerge to dev
    conditions:
      - and:
        - "base=dev"
        - "-draft"
    actions:
      queue:
        name: dev
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})

          {{ body }}

          Pull Request: https://github.com/{{ repository_full_name }}/pull/{{ number }}
      backport:
        branches:
          - prod
        assignees:
          - "{{ author }}"

  - name: automerge to prod
    conditions:
      - "base=prod"
    actions:
      queue:
        name: prod
