queue_rules:
  - name: dev

pull_request_rules:
  - name: automerge
    conditions:
      - and:
        - "base=main"
        - "draft=false"
    actions:
      queue:
        name: dev
        method: squash
        commit_message_template: >
          {{ title }} (#{{ number }})

          {{ body }}

          Pull Request: https://github.com/{{ repository-full-name }}/pulls/{{ number }}
